version: "3.9"

services:
    app:
        container_name: object-detector-api
        image: luisill0/obj-detector-api:latest
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        ports:
            - $PORT:3100